"""Network transport layer.

This module provides transport implementations:
- TCP transport with length-prefixed framing
- QASP-Discover for service discovery
- Registry-based agent discovery
"""

from .discover import (
    DEFAULT_AD_TTL,
    DEFAULT_DISCOVERY_TIMEOUT,
    MDNS_SERVICE_TYPE,
    WELL_KNOWN_PATH,
    CapabilityAdvertisement,
    DiscoveryClient,
    DiscoveryServer,
    ServiceEndpoint,
    create_advertisement,
    verify_advertisement,
)
from .exceptions import (
    AdvertisementError,
    ConnectionClosedError,
    ConnectionError,
    ConnectionRefusedError,
    ConnectionTimeoutError,
    DiscoveryError,
    DiscoveryTimeoutError,
    FramingError,
    ReceiveError,
    RegistryEntryError,
    RegistryQueryError,
    RegistrySignatureError,
    SendError,
    TransportError,
)
from .registry import (
    DEFAULT_REGISTRY_TTL,
    MAX_QUERY_RESULTS,
    AgentRegistry,
    CapEntry,
    RegistryEntry,
    RegistryQuery,
    RegistryResponse,
    create_registry_entry,
    get_agent_registry,
    match_capability,
    verify_registry_entry,
)
from .quic import (
    DEFAULT_QUIC_PORT,
    QASPQuicClient,
    QASPQuicServer,
    quic_connect,
    quic_serve,
)
from .tcp import (
    DEFAULT_READ_SIZE,
    LENGTH_PREFIX_SIZE,
    MAX_MESSAGE_SIZE,
    TCPServer,
    TCPTransport,
    connect,
    listen,
    serve,
)

__all__ = [
    "DEFAULT_AD_TTL",
    "DEFAULT_DISCOVERY_TIMEOUT",
    "DEFAULT_QUIC_PORT",
    "DEFAULT_READ_SIZE",
    "DEFAULT_REGISTRY_TTL",
    "LENGTH_PREFIX_SIZE",
    "MAX_MESSAGE_SIZE",
    "MAX_QUERY_RESULTS",
    "MDNS_SERVICE_TYPE",
    "WELL_KNOWN_PATH",
    "AdvertisementError",
    "AgentRegistry",
    "CapEntry",
    "CapabilityAdvertisement",
    "ConnectionClosedError",
    "ConnectionError",
    "ConnectionRefusedError",
    "ConnectionTimeoutError",
    "DiscoveryClient",
    "DiscoveryError",
    "DiscoveryServer",
    "DiscoveryTimeoutError",
    "FramingError",
    "QASPQuicClient",
    "QASPQuicServer",
    "ReceiveError",
    "RegistryEntry",
    "RegistryEntryError",
    "RegistryQuery",
    "RegistryQueryError",
    "RegistryResponse",
    "RegistrySignatureError",
    "SendError",
    "ServiceEndpoint",
    "TCPServer",
    "TCPTransport",
    "TransportError",
    "connect",
    "create_advertisement",
    "create_registry_entry",
    "discover",
    "get_agent_registry",
    "listen",
    "match_capability",
    "quic_connect",
    "quic_serve",
    "serve",
    "tcp",
    "verify_advertisement",
    "verify_registry_entry",
]
