"""QASP protocol implementation.

This module implements the core QASP protocol:
- QASPConnection: Sans-I/O connection management
- QASP-Shake: Post-quantum handshake protocol
- Capability tokens for access control
- Usage metering and settlement
"""

from .connection import QASPConnection
from .events import (
    AlertReceived,
    ConnectionClosed,
    ConnectionError,
    DataReceived,
    DataSent,
    DisputeEvidenceReceived,
    DisputeOpened,
    DisputeResolved,
    Event,
    HandshakeComplete,
    HandshakeFailed,
    HandshakeInitiated,
    MeterAckSent,
    MeterReportReceived,
    ResourceDenied,
    ResourceGranted,
    ResourceReleased,
    ResourceRequested,
    RevocationCascadeComplete,
    RevocationGracePeriodStarted,
    StreamClosed,
    StreamDataReceived,
    StreamOpened,
    TokenIssued,
    TokenRevoked,
    TokenVerified,
)
from .exceptions import (
    HandshakeAuthError,
    HandshakeError,
    HandshakeKEMError,
    HandshakeSuiteError,
    HandshakeTimeoutError,
    HandshakeVersionError,
)
from .handshake import (
    Handshake,
    HandshakeConfig,
    HandshakeErrorType,
    HandshakeFailure,
    HandshakeKeys,
    HandshakeState,
)
from .states import (
    VALID_TRANSITIONS,
    ConnectionState,
    ProtocolError,
    StateTransitionError,
    is_valid_transition,
)
from .revocation import (
    NORMAL_GRACE_PERIOD_SECONDS,
    CertificateRevocationList,
    InvalidRevocationError,
    RevocationAuthorityError,
    RevocationEntry,
    RevocationError,
    RevocationReason,
    RevocationUrgency,
    TokenAlreadyRevokedError,
    check_revocation,
    revoke_token,
)
from .stream import (
    Stream,
    StreamFlags,
    StreamFrame,
    StreamManager,
    StreamState,
)
from .aggregation import (
    DelegationChain,
    aggregate_sign,
    aggregate_verify_chain,
    attenuate_token_aggregate,
)
from .token_aggregation import (
    AggregatedPermission,
    ConstraintConflictError,
    TokenAggregationError,
    aggregate_tokens,
    check_action_permitted,
)

__all__ = [
    "AggregatedPermission",
    "ConstraintConflictError",
    "DelegationChain",
    "NORMAL_GRACE_PERIOD_SECONDS",
    "VALID_TRANSITIONS",
    "AlertReceived",
    "CertificateRevocationList",
    "ConnectionClosed",
    "ConnectionError",
    "ConnectionState",
    "DataReceived",
    "DataSent",
    "DisputeEvidenceReceived",
    "DisputeOpened",
    "DisputeResolved",
    "Event",
    "Handshake",
    "HandshakeAuthError",
    "HandshakeComplete",
    "HandshakeConfig",
    "HandshakeError",
    "HandshakeErrorType",
    "HandshakeFailed",
    "HandshakeFailure",
    "HandshakeInitiated",
    "HandshakeKEMError",
    "HandshakeKeys",
    "HandshakeState",
    "HandshakeSuiteError",
    "HandshakeTimeoutError",
    "HandshakeVersionError",
    "InvalidRevocationError",
    "MeterAckSent",
    "MeterReportReceived",
    "ProtocolError",
    "QASPConnection",
    "ResourceDenied",
    "ResourceGranted",
    "ResourceReleased",
    "ResourceRequested",
    "RevocationAuthorityError",
    "RevocationCascadeComplete",
    "RevocationEntry",
    "RevocationError",
    "RevocationGracePeriodStarted",
    "RevocationReason",
    "RevocationUrgency",
    "StateTransitionError",
    "Stream",
    "StreamClosed",
    "StreamDataReceived",
    "StreamFlags",
    "StreamFrame",
    "StreamManager",
    "StreamOpened",
    "StreamState",
    "TokenAggregationError",
    "TokenAlreadyRevokedError",
    "TokenIssued",
    "TokenRevoked",
    "TokenVerified",
    "aggregate_sign",
    "aggregate_tokens",
    "aggregate_verify_chain",
    "attenuate_token_aggregate",
    "check_action_permitted",
    "check_revocation",
    "is_valid_transition",
    "revoke_token",
]
