"""Message framing and serialization.

This module handles CBOR-based message encoding and decoding
for QASP protocol messages.
"""

from .codec import (
    FRAME_MAGIC,
    FRAME_VERSION,
    HEADER_SIZE,
    HMAC_SIZE,
    FrameHeader,
    FramingError,
    decode,
    decode_frame,
    encode,
    encode_frame,
)
from .messages import (
    Alert,
    ApplicationData,
    ChannelClose,
    ChannelOpen,
    ClientAuth,
    ClientHello,
    DelegationGrant,
    DelegationRequest,
    DisputeEvidence,
    DisputeOpen,
    DisputeVerdict,
    Message,
    MessageType,
    MeterAck,
    MeterReport,
    OCSPRequestMessage,
    OCSPResponseMessage,
    PriceAccept,
    PriceOffer,
    PriceRequest,
    ReconciliationRequest,
    ReconciliationResponse,
    ResourceDeny,
    ResourceGrant,
    ResourceRelease,
    ResourceRequest,
    ResourceSuspend,
    RevocationNotice,
    ServerHello,
    TokenRevocation,
)

__all__ = [
    "FRAME_MAGIC",
    "FRAME_VERSION",
    "HEADER_SIZE",
    "HMAC_SIZE",
    "Alert",
    "ApplicationData",
    "ChannelClose",
    "ChannelOpen",
    "ClientAuth",
    "ClientHello",
    "DelegationGrant",
    "DelegationRequest",
    "DisputeEvidence",
    "DisputeOpen",
    "DisputeVerdict",
    "FrameHeader",
    "FramingError",
    "Message",
    "MessageType",
    "MeterAck",
    "MeterReport",
    "OCSPRequestMessage",
    "OCSPResponseMessage",
    "PriceAccept",
    "PriceOffer",
    "PriceRequest",
    "ReconciliationRequest",
    "ReconciliationResponse",
    "ResourceDeny",
    "ResourceGrant",
    "ResourceRelease",
    "ResourceRequest",
    "ResourceSuspend",
    "RevocationNotice",
    "ServerHello",
    "TokenRevocation",
    "decode",
    "decode_frame",
    "encode",
    "encode_frame",
]
