"""Identity management for QASP.

This module implements:
- did:qasp decentralized identifiers for AI agent identity
- Owner-agent binding for authorization
- X.509-PQ certificate integration
"""

from qasp.identity.binding import (
    OwnerBinding,
    Permission,
    attenuate_binding,
    create_owner_binding,
    verify_binding_chain,
    verify_owner_binding,
)
from qasp.identity.did import (
    DID,
    DIDDocument,
    DIDRegistry,
    VerificationMethod,
    create_did,
    decode_public_key_multibase,
    encode_public_key_multibase,
    get_registry,
    resolve_did,
    verify_did,
    verify_did_signature,
)
from qasp.identity.exceptions import (
    BindingError,
    BindingExpiredError,
    BindingPermissionError,
    DHTEntryError,
    DIDError,
    DIDResolutionError,
    ExpiredSVIDError,
    IdentityError,
    InvalidBindingError,
    InvalidDIDError,
    InvalidSPIFFEIDError,
    KeyRotationError,
    SPIFFEError,
    SVIDVerificationError,
    StaleEntryError,
    ThresholdGroupError,
    TrustBundleError,
)
from qasp.identity.group import (
    ThresholdGroup,
    create_threshold_group,
    get_threshold_policy,
    is_threshold_did,
    register_threshold_group,
)
from qasp.identity.resolver import (
    DHTEntry,
    DIDResolverNetwork,
    InMemoryBackend,
    ResolverBackend,
    SQLiteBackend,
    create_dht_entry,
    get_resolver,
    resolve_did_document,
    verify_dht_entry,
)
from qasp.identity.rotation import (
    KeyRotationProof,
    commit_next_key,
    create_rotation_proof,
    rotate_key,
    verify_rotation_proof,
)
from qasp.identity.spiffe import (
    SPIFFEID,
    SVIDCertificate,
    TrustBundle,
    TrustBundleRegistry,
    get_trust_bundle_registry,
    parse_spiffe_id,
    parse_svid_from_x509,
    verify_svid,
    verify_svid_with_registry,
)

__all__ = [
    "DHTEntry",
    "DHTEntryError",
    "DID",
    "DIDDocument",
    "DIDError",
    "DIDRegistry",
    "DIDResolutionError",
    "DIDResolverNetwork",
    "ExpiredSVIDError",
    "IdentityError",
    "InMemoryBackend",
    "InvalidBindingError",
    "InvalidDIDError",
    "InvalidSPIFFEIDError",
    "KeyRotationError",
    "KeyRotationProof",
    "OwnerBinding",
    "Permission",
    "ResolverBackend",
    "SPIFFEID",
    "SPIFFEError",
    "SQLiteBackend",
    "SVIDCertificate",
    "SVIDVerificationError",
    "StaleEntryError",
    "TrustBundle",
    "TrustBundleError",
    "TrustBundleRegistry",
    "VerificationMethod",
    "ThresholdGroup",
    "ThresholdGroupError",
    "attenuate_binding",
    "BindingError",
    "BindingExpiredError",
    "BindingPermissionError",
    "commit_next_key",
    "create_dht_entry",
    "create_did",
    "create_owner_binding",
    "decode_public_key_multibase",
    "encode_public_key_multibase",
    "get_registry",
    "get_resolver",
    "get_trust_bundle_registry",
    "parse_spiffe_id",
    "parse_svid_from_x509",
    "resolve_did",
    "resolve_did_document",
    "rotate_key",
    "create_rotation_proof",
    "verify_binding_chain",
    "verify_dht_entry",
    "create_threshold_group",
    "get_threshold_policy",
    "is_threshold_did",
    "register_threshold_group",
    "verify_did",
    "verify_did_signature",
    "verify_owner_binding",
    "verify_rotation_proof",
    "verify_svid",
    "verify_svid_with_registry",
]
